name: Birthday Checker

on:
  schedule:
    -cron '0 8 * * *' #every day run time
  workflow_dispatch:    #allows for manual run

jobs:
  run-script: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run birthday script
        run: node birthday-bot/birthday.js
		
